Build image POC
ionos-cloud/paas-k8s-image pull request #1
Opened 2021-07-01 12:50 UTC by schegi

Implements: https://jira.sso.ionos.cloud/browse/PSC-1973

2021-08-12 15:47 UTC, piepmatz requested changes
In addition to the inline comments I have a few further questions.
- What about wireguard?
- Do you have a script or something floating around to set up an environment running `image-factory`?
- What happened to `dhclient.conf` currently written by kw-nodepool? Isn't it required?
- Looks like we don't have tickets yet to adapt kw-nodepool and kw-prespray for the new situation with stuff being moved here and into cloud-init, right?
- What about the configuration of `authorized_keys`? Can't this at least partly be done here?
- What about the "Fix permission for systemd-journald persistent storage" step from kw-prespray? Is it not required?
- What about the "Disable unneeded services" step from kw-prespray? Isn't there something on Ubuntu we don't need?

2021-08-12 15:47 UTC, piepmatz commented on scripts/build_static_configuration.sh
> +unswap() {
our `swapoff` ansible role does a bit more, e.g. partition things. isn't this required here?

2021-08-13 07:02 UTC, schegi commented on preseeds/k8s-1.18.20-ubuntu-20.04-LTS-server.cfg
> +    in-target apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main" && \
I found no way to install packages in a specific version using pkgsel so i had to do it in the late command, unfortunately the repos added using d-i apt-setup are not available in target during late command, so i had to add k8s repos this way.

2021-08-13 07:02 UTC, schegi commented on scripts/build_static_configuration.sh
> +unswap() {
there is no swap partition at this time.

2021-08-13 07:06 UTC, schegi commented on image-factory.conf
> +fedora_mirror=rsync://ftp.fau.de/fedora
The plan was to push our changes on image-factory.conf together with the preseed files into the 'official' ionos image build repo, so that they care about building and distributing our images. But you're i'll strip it.

2021-08-13 07:07 UTC, schegi commented on preseeds/k8s-1.18.20-ubuntu-20.04-LTS-server.cfg
> +    in-target apt-key add /tmp/apt-key.gpg && \
it's in /tmp so it should be gone on first boot.

2021-08-13 07:09 UTC, schegi commented on preseeds/k8s-1.18.20-ubuntu-20.04-LTS-server.cfg
> +    in-target wget "https://raw.githubusercontent.com/ionos-cloud/paas-k8s-image/kore-1973/image_poc_resources/scripts/build_static_configuration.sh" -O /tmp/build_static_configuration.sh && \
See my comment on your first, the idea was to have a dedicated repo with just our late command script, or maybe as you suggested something serving it. but as we plan to move to packer all this configuration will be done by ansible and we don't need this anymore.

2021-08-13 07:09 UTC, schegi commented on preseeds/k8s-1.21.2-ubuntu-20.04-LTS-server.cfg
> +    in-target apt-get install kubeadm=1.19.12-00 kubelet=1.21.2-00 -y && \
Let's call it leftover from tests.

2021-08-13 07:14 UTC, schegi commented
Regarding our additional questions,, i have gone through all i found in the different repos regarding node configuration together with Christof and we decided what is required and what can be dropped. But you are right we should look at this carefully, especially because i was not involved in the past in node configuration and i am not aware of all of the details.

- What about wireguard? Have to look it up.
- Do you have a script or something floating around to set up an environment running image-factory? No.
- What happened to dhclient.conf currently written by kw-nodepool? Isn't it required? 
- Looks like we don't have tickets yet to adapt kw-nodepool and kw-prespray for the new situation with stuff being moved here and into cloud-init, right? Right.
- What about the configuration of authorized_keys? Can't this at least partly be done here? Yes we could provide a default key in the image.
- What about the "Fix permission for systemd-journald persistent storage" step from kw-prespray? Is it not required? Not aware of it. I'll look it up./
- What about the "Disable unneeded services" step from kw-prespray? Isn't there something on Ubuntu we don't need? I'll find out.

2021-08-16 20:58 UTC, piepmatz requested changes

2021-08-16 20:58 UTC, piepmatz commented on scripts/build_static_configuration.sh
> +  chmod 644 /etc/ssh/sshd_config.d/AuthorizedKeysFile_config
Mh, another inconsistency: Before the latest batch of commits, all `chmod` modes had a leading 0.

2021-08-16 20:58 UTC, piepmatz commented on scripts/build_static_configuration.sh
> +  chmod 755 /var/log/journal
same here

2021-08-16 20:58 UTC, piepmatz commented on preseeds/k8s-1.18.20-ubuntu-20.04-LTS-server.cfg
> +d-i pkgsel/include string libnfs-utils dnsmasq-base containerd.io nfs-common cloud-init firewalld jq dnsmasq wireguard wireguard-tools
`wireguard-tools` are implicitly installed as part of `wireguard`

2021-08-16 20:58 UTC, piepmatz commented on scripts/build_static_configuration.sh
> +  echo "AuthorizedKeysFile /etc/ssh/authorized_keys_managed .ssh/authorized_keys" > /etc/ssh/sshd_config.d/AuthorizedKeysFile_config
Only `.conf` files are included from `/etc/ssh/sshd_config.d`.

2021-08-16 20:58 UTC, piepmatz commented on README.md
> +- dnsmasq
If you really want to maintain this list here, you'll need to add `wireguard` now. Btw, I updated this file (as announced some days ago).

2021-08-16 20:58 UTC, piepmatz commented on scripts/build_static_configuration.sh
> +  chmod 0755 ${KUBE_CERT_DIR}
`KUBE_MANIFESTS_DIR`

2021-08-16 20:58 UTC, piepmatz commented on files/containerd_config.toml
> +[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
now you appended it, but you need to prepend

2021-08-16 20:58 UTC, piepmatz commented on README.md
> +- dnsmasq-base
It's part of `dnsmasq`, so no need to mention and install it separately.

2021-08-16 20:58 UTC, piepmatz commented on preseeds/k8s-1.18.20-ubuntu-20.04-LTS-server.cfg
> +    in-target apt-key add /tmp/apt-key.gpg && \
Did you verify this?

2021-08-17 07:59 UTC, piepmatz commented on README.md
> +- dnsmasq
You still list `dnsmasq-base` and `wireguard-tools` here, even though you don't explicitly install them anymore.

2021-08-17 09:48 UTC, piepmatz approved these changes

2021-08-19 09:24 UTC, merged